---
title: "Getting Started with R at Te Kaunihera o Tāmaki Makaurau"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{prerequisites}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Welcome

Kia ora, and congratulations on choosing to use the R programming language at Te Kaunihera o Tāmaki Makaurau (Auckland Council)!

# Wait, why should I learn R?

That's a great question!

You're probably familiar with using Excel for working with data. Excel is a powerful and versatile tool that we all have access to, but I'm guessing you're here because you see the limitations of that software:

-   **Things can go wrong easily**: a simple mouse click can change important data; a stray keyboard entry can erase a crucial formula in cell B16, without which the value you need in cell AB16 won't show. Nobody wants this.
-   **You can't reproduce things**: all that work you put into preparing a *beautiful* table from this year's data? You'll need to do a lot of copying, pasting, and tweaking to get it working with next year's data. Plus: only you understand how everything in those cells work.
-   **It keeps crashing**: as your spreadsheets get bigger and bigger, as you start adding pivot tables and charts and all kinds of things it's going to take a while to load that thing onto your screen, and you run the risk of losing everything when it crashes as you're making important changes
* **It changes things in unexpected ways**: you pasted in some dates that Excel thinks are number, or numbers it thinks are dates. Sometimes, by trying to be helpful, Excel is making your life harder. I feel your pain.

If it feels like you're fighting against the tool, or that it feels like it's taken too long to do what you need, then you're in the right place.
